### ISSUE TITLE
flow-bin NPM package not finding binary on Windows?

### ISSUE THREAD

**Issue by Daniel15** [facebook/flow#2288]
I'm trying to configure a Windows AppVeyor build for Jest, but it's resulting in the following error while running `npm install`:
```
> flow-bin@0.30.0 postinstall C:\projects\jest\node_modules\flow-bin
> node lib/install.js
  × No binary found matching your system. It's probably not supported.
  × flow binary test failed
```

My understanding is that Flow v0.30 [adds support for Windows](https://flowtype.org/blog/2016/08/01/Windows-Support.html), so this should be working now, right?

**Comment by Daniel15** [comment]
Flow requires a 64-bit version of Node to be running. Needed to update the AppVeyor config to use 64-bit Node.js:
```
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version x64
```
