### ISSUE TITLE
[Website] .featurette height is too short for "Javascript, your way" section under 768px

### ISSUE THREAD

**Issue by claudiopro** [facebook/flow#4308]
The section **JAVASCRIPT, YOUR WAY** overlaps the section **EASY INTEGRATION** when the screen is narrower than 768px. Relevant code:

```css
@media (min-width: 768px) {
  .featurette {
    height: 8rem; /* <== */
    margin-top: 0;
    margin-bottom: 3rem;
  }
}
```

![screen shot 2017-07-04 at 9 57 04 am](https://user-images.githubusercontent.com/860099/27823199-3abd60b8-60a0-11e7-9105-a243308a004d.png)
